from aiogram.fsm.state import State, StatesGroup


# Состояние
class States(StatesGroup):
    phone = State()
    name = State()
    city = State()
    phone_code = State()
    message = State()
    avito_info = State()
    admin_change = State()
    report_date = State()
    cities_to_add = State()
    cities_to_remove = State()
    shop_price = State()
    add_location = State()
    previous_state = State()
    feedback = State()
    visible_feedbacks = State()
    visible_payments = State()
    ban = State()
    unban = State()
    sending_text = State()
    sending_locations = State()

    ids = State()
    admin_ids = State()
    shop_ids = State()
    cities_ids = State()
    make_admin_ids = State()
    report_ids = State()
    location_ids = State()
    feedback_admin_ids = State()
    payments_admin_ids = State()
    ban_ids = State()
    user_ids = State()
    sending_ids = State()
    subscribe_ids = State()

    feedback_ids = State()
    video_ids = State()
